version: '3.3'
services:
  dbserver:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=skdfksjkf
      - MYSQL_DATABASE=offerings_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    ports:
      - "9955:3306"
    volumes:
        - "~/volumes/mysql:/var/lib/mysql"
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ENVIRONMENT=PRODUCTION
      - ADMIN_PASSWORD=somepass
      - COLLECTION_PASSWORD=somepass2
      - SMTP_SERVER=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_SENDER=sender@sender.de
      - SMTP_RECIPIENTS=offering@sender.de
      - SMTP_PASSWORD=asdfasdfasdf
      - WAIT_HOSTS=dbserver:3306
      - WAIT_HOSTS_TIMEOUT=180
      - WAIT_AFTER_HOSTS=10
    ports:
     - "8100:3000"
     - "9229:9229"
    stdin_open: true
    tty: true